image:
  repository: inbucket/inbucket
  tag: sha-504a79a
  pullPolicy: Always

service:
  port:
    http: 9000
    smtp: 25
    pop3: 1100

extraEnv:
  INBUCKET_LOGLEVEL: "info"
  INBUCKET_MAILBOXNAMING: "local"
  INBUCKET_SMTP_ADDR: "0.0.0.0:2500"
  INBUCKET_SMTP_DOMAIN: "inbucket"
  INBUCKET_SMTP_MAXRECIPIENTS: "200"
  INBUCKET_SMTP_MAXMESSAGEBYTES: "10240000"
  INBUCKET_SMTP_DEFAULTACCEPT: "false"
  INBUCKET_SMTP_ACCEPTDOMAINS: "morjoff.com"
  INBUCKET_SMTP_REJECTDOMAINS: ""
  INBUCKET_SMTP_DEFAULTSTORE: "true"
  INBUCKET_SMTP_STOREDOMAINS: ""
  INBUCKET_SMTP_DISCARDDOMAINS: ""
  INBUCKET_SMTP_TIMEOUT: "300s"
  INBUCKET_SMTP_TLSENABLED: "false"
  INBUCKET_SMTP_TLSPRIVKEY: "cert.key"
  INBUCKET_SMTP_TLSCERT: "cert.crt"
  INBUCKET_POP3_ADDR: "0.0.0.0:1100"
  INBUCKET_POP3_DOMAIN: "inbucket"
  INBUCKET_POP3_TIMEOUT: "600s"
  INBUCKET_WEB_ADDR: "0.0.0.0:9000"
  INBUCKET_WEB_BASEPATH: ""
  INBUCKET_WEB_UIDIR: "ui"
  INBUCKET_WEB_GREETINGFILE: "ui/greeting.html"
  INBUCKET_WEB_TEMPLATECACHE: "true"
  INBUCKET_WEB_MAILBOXPROMPT: "@inbucket"
  INBUCKET_WEB_COOKIEAUTHKEY: ""
  INBUCKET_WEB_MONITORVISIBLE: "true"
  INBUCKET_WEB_MONITORHISTORY: "30"
  INBUCKET_STORAGE_TYPE: "memory"
  INBUCKET_WEB_PPROF: "false"
  INBUCKET_STORAGE_PARAMS: ""
  INBUCKET_STORAGE_RETENTIONPERIOD: "24h"
  INBUCKET_STORAGE_RETENTIONSLEEP: "50ms"
  INBUCKET_STORAGE_MAILBOXMSGCAP: "500"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: inbucket.morjoff.com
      paths:
        - path: /
          backend:
            serviceName: inbucket.local
            servicePort: 80
  tls:
    - secretName: inbucket.morjoff.com
      hosts:
        - inbucket.morjoff.com
