---
- name: Install Xray
  ansible.builtin.shell: bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
  args:
    executable: /bin/bash
  changed_when: true

- name: Save Xray config
  ansible.builtin.template:
    src: server_config.json.j2
    dest: /usr/local/etc/xray/config.json
    mode: '0644'

- name: Restart Xray service asynchronously
  ansible.builtin.systemd:
    name: xray
    state: restarted
  async: 30
  poll: 0

- name: Render xray client config locally (JSON)
  ansible.builtin.template:
    src: client_config.j2
    dest: "~/vpn/{{ inventory_hostname }}_config.json"
    mode: '0600'
  delegate_to: localhost

- name: Render xray client config locally (URI)
  ansible.builtin.template:
    src: client_uri.j2
    dest: "~/vpn/{{ inventory_hostname }}_uri.txt"
    mode: '0600'
  delegate_to: localhost
