---
- name: Allow ports 22, 23, 443 UFW
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '22'
    - '80'
    - '443'

- name: Ensure UFW is enabled
  community.general.ufw:
    state: enabled

- name: Download headscale package
  ansible.builtin.get_url:
    url: "{{ headscale_url }}"
    dest: "/tmp/headscale_{{ headscale_version }}_linux_{{ headscale_arch }}.deb"
    checksum: "sha256:{{ headscale_checksum }}"
    mode: '0644'

- name: Install headscale package
  ansible.builtin.apt:
    deb: "/tmp/headscale_{{ headscale_version }}_linux_{{ headscale_arch }}.deb"

- name: Configure headscale
  ansible.builtin.template:
    src: "config.yaml.j2"
    dest: "{{ headscale_config_file_path }}"
    owner: root
    group: root
    mode: '0644'

- name: Enable and start headscale service
  ansible.builtin.systemd:
    name: headscale
    enabled: true
    state: started
