---
- name: Allow ports 22, 23, 443 UFW
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '22'
    - '80'
    - '443'

- name: Ensure UFW is enabled
  ansible.builtin.ufw:
    state: enabled

- name: Download headscale package
  get_url:
    url: "{{ headscale_url }}"
    dest: "/tmp/headscale_{{ headscale_version }}_linux_{{ headscale_arch }}.deb"
    checksum: "sha256:{{ headscale_checksum }}"

- name: Install headscale package
  apt:
    deb: "/tmp/headscale_{{ headscale_version }}_linux_{{ headscale_arch }}.deb"

- name: Configure headscale
  template:
    src: "config.yaml.j2"
    dest: "{{ config_file_path }}"
    owner: root
    group: root
    mode: '0644'

- name: Enable and start headscale service
  systemd:
    name: headscale
    enabled: yes
    state: started

- name: Verify headscale service is running
  command: systemctl status headscale
  register: headscale_status
  ignore_errors: yes

- name: Display headscale service status
  debug:
    var: headscale_status

- name: Update DuckDNS
  command: >
    curl -s "https://www.duckdns.org/update?domains={{ duckdns_domain }}&token={{ duckdns_token }}&ip={{ ansible_default_ipv4.address }}"
  register: duckdns_update_result

- name: Display DuckDNS update result
  debug:
    var: duckdns_update_result
