---
- name: Parse users YAML
  ansible.builtin.set_fact:
    xray_users: "{{ xray_users_b64 | b64decode | from_json }}"

- name: Select xray_client user
  ansible.builtin.set_fact:
    xray_client_user: >-
      {{
        xray_users
        | selectattr('name', 'equalto', 'xray_client')
        | list
        | first
      }}

- name: Install Xray
  ansible.builtin.shell: bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
  args:
    executable: /bin/bash
  changed_when: true

- name: Download Loyalsoldier geoip.dat
  ansible.builtin.get_url:
    url: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
    dest: /usr/local/share/xray/geoip.dat
    mode: "0644"

- name: Register WARP device (idempotent)
  ansible.builtin.include_tasks: warp_register.yml
  when: warp_outbound_enabled


- name: Save Xray config
  ansible.builtin.copy:
    dest: /usr/local/etc/xray/config.json
    mode: '0644'
    content: "{{ lookup('template', 'server_config.j2') | from_json | to_nice_json }}"

- name: Restart Xray service
  ansible.builtin.systemd:
    name: xray
    state: restarted

- name: Generate client configs
  ansible.builtin.include_tasks: client_configs.yml
