cluster:
  name: my-cluster
destinations:
  grafana-cloud-metrics:
    type: prometheus
    url: https://prometheus-prod-10-prod-us-central-0.grafana.net./api/prom/push
    auth:
      type: basic
      username: "413638"
      # password:
  grafana-cloud-logs:
    type: loki
    url: https://logs-prod3.grafana.net./loki/api/v1/push
    auth:
      type: basic
      username: "205789"
      # password:
clusterMetrics:
  enabled: true
  collector: alloy-metrics
hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
  windowsHosts:
    enabled: true
clusterEvents:
  enabled: true
  collector: alloy-singleton
podLogsViaLoki:
  enabled: true
  collector: alloy-logs
nodeLogs:
  enabled: true
  collector: alloy-logs
collectors:
  alloy-metrics:
    presets:
      - clustered
      - statefulset
  alloy-singleton:
    presets:
      - singleton
  alloy-logs:
    presets:
      - filesystem-log-reader
      - daemonset
collectorCommon:
  alloy:
    remoteConfig:
      enabled: true
      url: https://fleet-management-prod-001.grafana.net
      auth:
        type: basic
        username: "356612"
        # password:
telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
  windows-exporter:
    deploy: true