---
- name: Check mandatory variables are defined
  assert:
    that:
      - GCLOUD_STACK_ID is defined
      - GCLOUD_API_KEY is defined

- name: Populate service facts
  service_facts:
- name: Install the Grafana agent
  shell: >
    ARCH=amd64
    GCLOUD_STACK_ID={{ GCLOUD_STACK_ID | quote }}
    GCLOUD_API_KEY={{ GCLOUD_API_KEY | quote }}
    GCLOUD_API_URL="https://integrations-api-us-central.grafana.net"
    /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/grafana/agent/release/production/grafanacloud-install.sh)"
  when: "'grafana-agent' not in services"

- name: Set hostname
  replace:
    path: /etc/grafana-agent.yaml
    regexp: hostname
    replace: "{{ inventory_hostname }}"
  notify:
    - restart grafana-agent
