k3s_server:
  hosts:
    k3s-server:
      ansible_host: 193.181.212.97
      ansible_user: root
k3s_agent:
  vars:
    k3s_server_host: k3s-server
  hosts:
    k3s-agent:
      ansible_host: 193.181.216.56
      ansible_user: root
