xray:
  vars:
    ansible_user: root
    grafana_alloy_collector_attrs:
      reverse_proxy: caddy
    xray_xhttp_port_internal: 10000

  hosts:
    ru_firstvds:
      ansible_host: 188.120.246.74
#      grafana_repo_mirror: yandex
      domain: clumsypanda.mooo.com
#      cdn_domain: 3v6ocwf108.cdn.twcstorage.ru
#      server_ip: 151.236.89.224
      next_address: quietotter.mooo.com
      xray_xhttp_extra_settings: &xray_xhttp_extra_settings
#        uplinkHTTPMethod: GET
#        xPaddingObfsMode: true
#        xPaddingPlacement: header
#        xPaddingHeader: b3
#        xPaddingMethod: tokenish
#        sessionPlacement: query
#        sessionKey: api_key
#        seqPlacement: query
#      next_address_xray_xhttp_extra_settings: *xray_xhttp_extra_settings
      warp_outbound_enabled: false
      local_exit_rules:
        - type: field
          domain: [ "domain:ru", "domain:xn--p1ai" ]
          outboundTag: direct
    #        - type: field
    #          ip: [ "geoip:ru" ]
    #          outboundTag: direct

    dk_webdock:
      ansible_host: 92.113.145.63
      domain: quietotter.mooo.com
#      cdn_domain: 3w6i2ij759.cdn.twcstorage.ru
#      server_ip: 151.236.89.224
      warp_outbound_enabled: true
#      xray_xhttp_extra_settings: *xray_xhttp_extra_settings

    nl_llhost:
      ansible_host: 45.85.117.151
      domain: brisklizard.mooo.com
      warp_outbound_enabled: true

  children:
    xray_publish:
      hosts:
        ru_firstvds:
