xray_portal:
  hosts:
    ruvds_msk_01:
      ansible_host: 176.113.82.170
      ansible_user: root
      domain: scarletfalcon.mooo.com
      grafana_repo_mirror: yandex
      xray_portal_reality_server_name: slickjump.ru
      grafana_alloy_collector_attrs:
        reverse_proxy: caddy

xray_bridge:
  hosts:
    sg_nl_01:
      ansible_host: 45.149.154.132
      ansible_user: root
      portal_domain: yagate.morjoff.com
      xray_bridge_outbound_tag: outgoing_xhttp
      xray_portal_reality_server_name: slickjump.ru
      grafana_alloy_collector_attrs:
        reverse_proxy: caddy
