xray_chain:
  hosts:
    firstvds_relay:
      ansible_host: 188.120.246.74
      ansible_user: root
      domain: clumsypanda.mooo.com
      next_address: quietotter.mooo.com
      grafana_repo_mirror: yandex
      grafana_alloy_collector_attrs:
        reverse_proxy: caddy

    webdock_exit:
      ansible_host: 92.113.145.63
      ansible_user: root
      domain: quietotter.mooo.com
      grafana_alloy_collector_attrs:
        reverse_proxy: caddy
