---
- name: Check mandatory variables are defined
  ansible.builtin.assert:
    that:
      - K3S_TOKEN is defined

- name: Comment out swap entries in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'

- name: Check if UFW is installed
  ansible.builtin.stat:
    path: /usr/sbin/ufw
  register: ufw_binary

- name: Disable UFW
  community.general.ufw:
    state: disabled
  when: ufw_binary.stat.exists

- name: Gather facts about services
  ansible.builtin.service_facts:

- name: Install k3s
  args:
    executable: /usr/bin/bash
  ansible.builtin.shell: >
    set -o pipefail &&
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version | quote }} INSTALL_K3S_EXEC="server
      --token {{ K3S_TOKEN | quote }}
      --advertise-address {{ ansible_facts['tailscale0']['ipv4']['address'] }}
      --flannel-iface tailscale0
      --node-ip {{ ansible_facts['tailscale0']['ipv4']['address'] }}
      --cluster-cidr {{ k3s_pod_cidr }}
      --service-cidr {{ k3s_service_cidr }}
      --disable-cloud-controller
      --tls-san {{ inventory_hostname }}
      {% if k3s_cluster_init | default(false) %}--cluster-init{% elif k3s_init_host | default('') != '' and k3s_init_host != inventory_hostname %}--server https://{{ k3s_init_host }}:6443{% endif %}" sh -
  when: "'k3s' not in ansible_facts.services"
  changed_when: true

- name: Ensure k3s is in a running state
  ansible.builtin.service:
    name: k3s
    state: started

- name: Taint server node to prevent workload scheduling
  ansible.builtin.command:
    cmd: k3s kubectl taint node {{ inventory_hostname }} node-role.kubernetes.io/control-plane=:NoSchedule --overwrite
  changed_when: false

- name: Deploy Traefik HelmChartConfig
  ansible.builtin.template:
    src: traefik-config.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
    mode: "0644"

- name: Fetch kubeconfig
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/k3s-kubeconfig
    flat: true

- name: Set kubeconfig permissions
  ansible.builtin.file:
    path: ~/.kube/k3s-kubeconfig
    mode: "0600"
  delegate_to: localhost
