integrations:
  node_exporter:
    enabled: true
    relabel_configs:
    - replacement: {{ inventory_hostname }}
      target_label: instance
  agent:
    enabled: true
  prometheus_remote_write:
  - basic_auth:
      password: {{ GCLOUD_API_KEY }}
      username: {{ GCLOUD_HOSTED_METRICS_ID }}
    url: {{ GCLOUD_HOSTED_METRICS_URL }}
logs:
  configs:
  - clients:
    - basic_auth:
        password: {{ GCLOUD_API_KEY }}
        username: {{ GCLOUD_HOSTED_LOGS_ID }}
      url: {{ GCLOUD_HOSTED_LOGS_URL }}
    name: integrations
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
    - job_name: integrations/node_exporter_journal_scrape
      journal:
        max_age: 24h
        labels:
          instance: {{ inventory_hostname }}
          job: integrations/node_exporter
      relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__boot_id']
        target_label: 'boot_id'
      - source_labels: ['__journal__transport']
        target_label: 'transport'
      - source_labels: ['__journal_priority_keyword']
        target_label: 'level'
metrics:
  configs:
  - name: {{ inventory_hostname }}
    remote_write:
    - basic_auth:
        password: {{ GCLOUD_API_KEY }}
        username: {{ GCLOUD_HOSTED_METRICS_ID }}
      url: {{ GCLOUD_HOSTED_METRICS_URL }}
  global:
    scrape_interval: 60s
  wal_directory: /tmp/grafana-agent-wal
