---
- name: Turn off swap
  ansible.builtin.command: swapoff -a
  changed_when: true

- name: Remove swapfile entry from /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '.*swap.*'

- name: Remove the swapfile
  ansible.builtin.file:
    path: /swapfile
    state: absent
