---
- name: Check mandatory variables are defined
  ansible.builtin.assert:
    that:
      - TIER is defined
      - K3S_TOKEN is defined

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Disable UFW
  community.general.ufw:
    state: disabled

- name: Gather facts about services
  ansible.builtin.service_facts:

- name: Install k3s
  args:
    executable: /usr/bin/bash
  ansible.builtin.shell: >
    set -o pipefail &&
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent
      --debug
      --server https://{{ TIER }}-k3s-server-0:6443
      --flannel-iface tailscale0
      --node-ip {{ ansible_tailscale0.ipv4.address }}
      --token {{ K3S_TOKEN | quote }}" sh -
  when: "'k3s-agent' not in services"
  changed_when: true

- name: Ensure k3s is in a running state
  ansible.builtin.systemd:
    name: k3s-agent
    state: started
    enabled: true
