---
- name: Reload sshd
  ansible.builtin.systemd:
    name: "{{ ssh_reverse_tunnel_client_sshd_service }}"
    state: reloaded
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
