apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/name: {{ include "inbucket.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "inbucket.chart" . }}
  name: {{ .Release.Name }}-auth-middleware
  namespace: {{ .Release.Namespace }}
spec:
  basicAuth:
    secret: {{ .Release.Name }}-auth-secret
    removeHeader: true
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ include "inbucket.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "inbucket.chart" . }}
  name: {{ .Release.Name }}-auth-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
data:
  username: dXNlcg== # username: user
  password: {{ randAlphaNum 32 | b64enc }}