apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "inbucket.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "inbucket.chart" . }}
  name: {{ include "inbucket.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "inbucket.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "inbucket.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "inbucket.chart" . }}
    spec:
      containers:
        - name: {{ include "inbucket.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          envFrom:
          - configMapRef:
              name: {{ include "inbucket.name" . }}-configmap
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: smtp
              containerPort: 2500
              protocol: TCP
            - name: pop3
              containerPort: 1100
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
          args:
            - --provider=google
            - --upstream=http://127.0.0.1:9000
            - --cookie-secret={{ .Values.oauth2Proxy.cookieSecret }}
            - --client-id={{ .Values.oauth2Proxy.clientId }}
            - --client-secret={{ .Values.oauth2Proxy.clientSecret }}
            - --cookie-secure=false
            - --reverse-proxy=true
            - --request-logging=true
            - --standard-logging=true
            - --auth-logging=true
            - --http-address=0.0.0.0:4180
            - --authenticated-emails-file=/etc/oauth2-proxy/authenticated-emails-file 
          volumeMounts:
            - name: authenticated-emails
              mountPath: /etc/oauth2-proxy/authenticated-emails-file
              subPath: authenticated-emails-file  # specify file name
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secrets
                  key: client_id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secrets
                  key: client_secret
          ports:
            - name: proxy
              containerPort: 4180
              protocol: TCP
      volumes:
        - name: authenticated-emails
          configMap:
            name: {{ include "inbucket.name" . }}-authenticated-emails
