apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inbucket.name" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inbucket.labels" . | nindent 4 }}
data:
{{ toYaml .Values.extraEnv | indent 2 }}
