apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inbucket.name" . }}-authenticated-emails
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inbucket.labels" . | nindent 4 }}
data:
  authenticated-emails-file: |
    {{- range .Values.authenticatedEmails }}
    {{ . }}
    {{- end }}
