apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inbucket.labels" . | nindent 4 }}
type: Opaque
data:
  client_id: {{ .Values.oauth2Proxy.clientId | b64enc }}
  client_secret: {{ .Values.oauth2Proxy.clientSecret | b64enc }}
  cookie_secret: {{ randAlphaNum 16 | b64enc }}
