---
- name: Deploy headscale
  hosts: headscale

  roles:
    - role: nftables
      vars:
        nftables_full_flush: true
        nftables_allowed_tcp:
          - 22
          - 443
        nftables_allowed_udp:
          - 443
    - role: grafana_alloy
    - role: headscale
    - role: ssh_hardening
