---
- name: Maintain all hosts
  hosts: all

  tasks:
    - name: update all installed packages using APT module
      apt:
        name: "*"
        state: latest
        update_cache: true
        only_upgrade: true
