---
- name: Maintain all hosts
  hosts: all

  tasks:
    - name: Update all installed packages to the latest version
      apt:
        name: "*"
        state: latest
        update_cache: true
        only_upgrade: true

    - name: Check if a reboot is required
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required
        get_checksum: no

    - name: Reboot the server if a reboot is required
      reboot:
      when: reboot_required_file.stat.exists

    - name: Wait for the server to become reachable after reboot
      wait_for_connection:
        timeout: 300
      when: reboot_required_file.stat.exists

