---
- name: Set up VPN instance
  hosts: vpn

  vars_prompt:
    - name: tailscale_auth_key
      prompt: Enter the Tailscale Auth key

    - name: GCLOUD_STACK_ID
      prompt: GCLOUD_STACK_ID

    - name: GCLOUD_API_KEY
      prompt: GCLOUD_API_KEY

  roles:
    - role: grafana_agent
    - role: tailscale
    - role: ssh_hardening
