---
- name: Deploy Xray chain
  hosts: xray
  roles:
    - role: ufw_base
      ufw_allowed_tcp:
        - 22
        - 80
        - 443
        - 8443
      ufw_allowed_udp:
        - 443
    - role: grafana_alloy
    - role: freedns
      when: dns == 'freedns'
    - role: xray
    - role: caddy_proxy
    - role: ssh_hardening

- name: Setup config publishing
  hosts: xray_publish
  roles:
    - role: xray_publish
